"""The failure report: where the model missed, and what data has not been tried.

This is the input to the weekly loop. A Claude Code session reads it, proposes one candidate
feature, and the harness in candidates.py accepts or rejects it. The report is generated by the
pipeline rather than written by hand so that the starting point is the same evidence every week,
not whatever happened to be memorable.

It is deliberately blunt about how little room there is. The research measured the total remaining
headroom at under 7%, and found error spread evenly across situations rather than concentrated in
nameable ones — so a report that highlighted "interesting" cases would mostly be highlighting noise
and inviting exactly the kind of story-telling the promotion gate exists to reject.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import pandas as pd

from nfl_pipeline.predict.models import PredictionModel, baseline_predictions

# Columns the feature store carries that no model currently trains on. These are the honest place
# to look for a new feature, because everything else has already been tried.
UNTRIED_NOTE = """Datasets in the warehouse that no feature currently uses:
  - fct_player_week_advanced: yards before/after contact, pressure rate, play-action and motion
    rates, screen and no-huddle rates
  - stg_ngs: separation, cushion, air-yards share, time to throw, stacked-box rate
  - stg_participation: personnel groupings and who was on the field (TRAINING ONLY - it is a
    post-season release and can never be available for a live week)
  - depth_charts: listed role, which is not the same as snap share
"""


@dataclass
class FailureReport:
    season: int
    week: int
    player_games: int
    mae: float
    baseline_mae: float
    worst: pd.DataFrame
    by_position: pd.DataFrame
    by_tier: pd.DataFrame

    def to_markdown(self) -> str:
        lines = [
            f"# Where the model missed: {self.season} week {self.week}",
            "",
            f"{self.player_games} graded player-games. Average error {self.mae:.3f} against "
            f"{self.baseline_mae:.3f} for the best simple baseline "
            f"(margin {self.baseline_mae - self.mae:+.3f}).",
            "",
            "## By position",
            "",
            _table(self.by_position),
            "",
            "## By how much the player had recently been scoring",
            "",
            _table(self.by_tier),
            "",
            "## The ten biggest misses",
            "",
            "Individually these are mostly noise — a single game is not evidence. They are here to",
            "read for a *pattern*, and a pattern is only worth proposing if it can be written as a",
            "feature that would have been computable before kickoff.",
            "",
            _table(self.worst),
            "",
            "## What has not been tried",
            "",
            UNTRIED_NOTE,
            "## The bar",
            "",
            "A candidate ships only if it beats the champion by more than 0.05 mean absolute error",
            "on a walk-forward replay and keeps interval coverage between 0.75 and 0.85. Most will",
            "not. The research already ruled out adaptive weights, per-player bias correction and",
            "role-change heuristics, so do not propose those again; they are in the ledger.",
        ]
        return "\n".join(lines)


def _table(frame: pd.DataFrame) -> str:
    if frame.empty:
        return "_none_"
    header = "| " + " | ".join(frame.columns) + " |"
    rule = "|" + "|".join("---" for _ in frame.columns) + "|"
    rows = [
        "| " + " | ".join(_cell(value) for value in row) + " |"
        for row in frame.itertuples(index=False)
    ]
    return "\n".join([header, rule, *rows])


def _cell(value) -> str:
    if isinstance(value, float):
        return f"{value:.2f}"
    return str(value)


def analyze_week(
    graded: pd.DataFrame, names: pd.DataFrame | None = None, worst: int = 10
) -> FailureReport:
    """Break one graded week down into the few views that are worth looking at.

    `graded` is the locked predictions joined to what happened: it must carry `points`, `actual_ppr`
    and the recent-form columns the baselines need.
    """
    rows = graded[graded.actual_ppr.notna()].copy()
    if rows.empty:
        raise ValueError("no graded rows to analyse")

    rows["error"] = rows.actual_ppr - rows.points
    rows["absolute_error"] = rows.error.abs()
    baselines = baseline_predictions(rows)
    best_name = min(baselines, key=lambda n: float(np.mean(np.abs(rows.actual_ppr - baselines[n]))))
    rows["baseline_error"] = (rows.actual_ppr - baselines[best_name]).abs()

    by_position = (
        rows.groupby("position_group")
        .agg(
            players=("absolute_error", "size"),
            model=("absolute_error", "mean"),
            baseline=("baseline_error", "mean"),
        )
        .assign(margin=lambda d: d.baseline - d.model)
        .reset_index()
    )
    rows["tier"] = pd.cut(
        rows.ppr_mean5.fillna(0),
        [-0.01, 4, 8, 13, 100],
        labels=["under 4", "4-8", "8-13", "13+"],
    )
    by_tier = (
        rows.groupby("tier", observed=True)
        .agg(
            players=("absolute_error", "size"),
            model=("absolute_error", "mean"),
            baseline=("baseline_error", "mean"),
        )
        .assign(margin=lambda d: d.baseline - d.model)
        .reset_index()
    )

    biggest = rows.nlargest(worst, "absolute_error")
    if names is not None:
        biggest = biggest.merge(names, on="player_id", how="left")
        biggest["player"] = biggest.display_name.fillna(biggest.player_id)
    else:
        biggest["player"] = biggest.player_id
    biggest = biggest[["player", "position_group", "points", "actual_ppr", "error"]].rename(
        columns={"position_group": "pos", "points": "projected", "actual_ppr": "actual"}
    )

    return FailureReport(
        season=int(rows.season.iloc[0]),
        week=int(rows.week.iloc[0]),
        player_games=len(rows),
        mae=float(rows.absolute_error.mean()),
        baseline_mae=float(rows.baseline_error.mean()),
        worst=biggest,
        by_position=by_position,
        by_tier=by_tier,
    )


def eligible_for_report(features: pd.DataFrame, season: int, week: int) -> pd.DataFrame:
    """The rows a week's report should cover: the population that actually gets published."""
    week_rows = features[(features.season == season) & (features.week == week)]
    return PredictionModel.eligible(PredictionModel.predictable(week_rows))
